# Define named volumes at the top level, even though we use bind mounts for them in dev.
# This makes it consistent with the prod setup in terms of volume *names*.
volumes:
  media-data:
  upload-data:
  config-data:

services:
  api:
    image: python:3.11-slim
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
      # Bind mount local directories to the paths corresponding to named volumes
      - ./media-data:/media
      - ./upload-data:/uploads
      - ./config-data:/config
    ports:
      - "8000:8000"
    command: >
      sh -c "apt-get update && apt-get install -y --no-install-recommends ffmpeg && \
             pip install --no-cache-dir -r requirements.txt && \
             uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - PYTHONUNBUFFERED=1

  web:
    image: node:22-alpine
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install &&
             npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development
