import { precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';

// Precache all assets generated by the build process.
precacheAndRoute((self as any).__WB_MANIFEST);

// Network First strategy for API calls
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst()
);

// Ignore HLS segments (files ending with .ts)
registerRoute(
  ({ url }) => url.pathname.endsWith('.ts'),
  () => {
    // Do nothing, effectively ignoring these requests
    // so they are handled by the browser as usual.
  }
);

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    (self as any).skipWaiting();
  }
});
